# Generated by Django 5.0.7 on 2024-08-13 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.BooleanField(default=False)),
                ('button_theme_color', models.CharField(blank=True, max_length=7, null=True)),
                ('clip_theme_color', models.CharField(blank=True, max_length=7, null=True)),
                ('background_theme_color', models.CharField(blank=True, max_length=7, null=True)),
                ('text_theme_color', models.CharField(blank=True, max_length=7, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to_action_text', models.CharField(blank=True, max_length=255, null=True)),
                ('media_title', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('theme_color', models.CharField(blank=True, max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.BooleanField(default=False)),
                ('button_theme_color', models.CharField(blank=True, max_length=7, null=True)),
                ('clip_theme_color', models.CharField(blank=True, max_length=7, null=True)),
                ('background_theme_color', models.CharField(blank=True, max_length=7, null=True)),
                ('text_theme_color', models.CharField(blank=True, max_length=7, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to_action_text', models.CharField(blank=True, max_length=255, null=True)),
                ('media_title', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_type', models.CharField(choices=[('Clearance Sales', 'Clearance Sale'), ('Flash SALES', 'Flash Sale'), ('Special Deals', 'Special Deal'), ('Bestseller', 'Best Selling Product')], max_length=50)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('paymentMethod', models.CharField(blank=True, max_length=200, null=True)),
                ('taxPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('shippingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('paidAt', models.DateTimeField(blank=True, null=True)),
                ('isDelivered', models.BooleanField(default=False)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deliveryPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('deliveryTerms', models.TextField(blank=True, null=True)),
                ('deliveryDays', models.IntegerField(blank=True, null=True)),
                ('_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('media', models.BooleanField(default=False)),
                ('button_theme_color', models.CharField(blank=True, max_length=7, null=True)),
                ('clip_theme_color', models.CharField(blank=True, max_length=7, null=True)),
                ('background_theme_color', models.CharField(blank=True, max_length=7, null=True)),
                ('text_theme_color', models.CharField(blank=True, max_length=7, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to_action_text', models.CharField(blank=True, max_length=255, null=True)),
                ('media_title', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('SKU', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('countInStock', models.IntegerField(blank=True, default=0, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('brands', models.ManyToManyField(blank=True, to='base.brand')),
                ('categories', models.ManyToManyField(blank=True, to='base.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('special_offers', models.ManyToManyField(blank=True, related_name='products', to='base.specialoffer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('shippingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('deliveryDetails', models.TextField(blank=True, null=True)),
                ('_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategory_images/')),
                ('categories', models.ManyToManyField(blank=True, related_name='subcategory_set', to='base.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='products', to='base.subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='parent_categories', to='base.subcategory'),
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thumbnails/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='VariationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='base.variationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='base.product')),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.variationtype')),
                ('values', models.ManyToManyField(related_name='variations', to='base.variationvalue')),
            ],
        ),
    ]
