# Generated by Django 5.0.7 on 2024-07-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_brand_category_variationtype_remove_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryTerms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='deliveryDetails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
