# Generated by Django 5.0.7 on 2024-07-19 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order_deliverydays_order_deliveryprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='value',
        ),
        migrations.CreateModel(
            name='VariationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='base.variationtype')),
            ],
        ),
        migrations.AddField(
            model_name='variation',
            name='values',
            field=models.ManyToManyField(related_name='variations', to='base.variationvalue'),
        ),
    ]
