# Generated by Django 5.0.7 on 2024-08-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_media_img_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='img',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='media_images/'),
        ),
    ]
