# Generated by Django 5.0.7 on 2024-08-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_specialoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='special_offers',
            field=models.ManyToManyField(blank=True, related_name='products', to='base.specialoffer'),
        ),
    ]
