# Generated by Django 5.0.7 on 2024-09-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_category_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='category',
            name='isMajorCategory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
