# Generated by Django 5.0.7 on 2024-09-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_category_gender_subcategory_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='gender',
        ),
    ]
