# Generated by Django 5.0.7 on 2024-09-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_category_gender_remove_subcategory_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isMajorCategory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.category'),
        ),
    ]
