# Generated by Django 5.0.7 on 2024-09-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_category_ismajorcategory_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', "Men's"), ('women', "Women's"), ('unisex', 'Unisex')], max_length=10, null=True),
        ),
    ]
